title: Multimodal Interaction in Face-to-Face Interactions
description: EMNLP Workshop on Multimodal Interaction in Face-to-Face Interactions
url: ""
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

social:
  email: mint.organizers@gmail.com

editions:
  - year: 2026
    location: EMNLP 2026, Budapest, Hungary
 