title: SWiFT-MLP
description: Semi-Automated Workflows for Facilitating Multimodal Language Processing
url: ""
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

cfp:
  registration_link: "https://survey.academiccloud.de/f/435484?lang=en"

social:
  email: dr.esam.ghaleb@gmail.com

editions:
  - year: 2026
    location: MMSYM 2026, Leuven, Belgium
